os:
  - linux
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback

before_install:
  - chmod +x ./tool/travis/test.sh
  - chmod +x ./tool/travis/analyze.sh

sudo: required

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable ../flutter
  - export PATH="$PATH":`pwd`/../flutter/bin
  - export PATH="$PATH":`pwd`/../flutter/bin/cache/dart-sdk/bin
  - flutter config --no-analytics
  - flutter doctor
  - export FLUTTER_SDK=`pwd`/../flutter
  - gem install coveralls-lcov
  - flutter pub global activate dart_style
  - flutter packages get || exit -1;

jobs:
  include:
    - stage: quality
      name: "Tests"
      script: ./tool/travis/test.sh
    - stage: quality
      name: "Analyze"
      script: ./tool/travis/analyze.sh

stages:
  - quality

branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pub-cache