name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: 2.0.0
  device_info: 1.0.0
  dio: 3.0.10
  flutter_cache_manager: 2.1.1
  flutter_secure_storage: 3.3.5
  flutter_svg: 0.19.1
  json_serializable: 3.5.0
  injectable: 1.0.7
  get_it: 5.0.6
  mockito: 4.1.3
  moor: 3.4.0
  moor_ffi: 0.8.0
  niddler_dart: 0.10.4
  path: 1.8.0-nullsafety.1
  path_provider: 1.6.22
  provider: 4.3.2+2
  retrofit: 1.3.4+1
  scroll_when_needed: 1.0.0
  shared_preferences: 0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.0
  flutter_launcher_icons: ^0.8.1
  icapps_generator: 0.3.0
  icapps_license: 0.0.6
  icapps_translations: 3.0.5
  injectable_generator: 1.0.7
  model_generator: 3.3.0
  moor_generator: 3.4.0
  retrofit_generator: 1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

icapps_translations:
  api_key: 'lIWZxNlOz3d461rVMeh3dw' #TODO Update this to the correct api key
  default_language: 'nl'
  languages: ['nl','en']

icapps_license:
  licenses:
    moor_ffi: https://raw.githubusercontent.com/simolus3/moor/develop/moor_ffi/LICENSE