name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  device_info: ^2.0.3
  dio: ^4.0.0
  drift: ^1.1.0
  drift_db_viewer: ^1.0.0
  drift_inspector: ^1.0.0
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  get: ^4.6.5
  get_it: ^7.2.0
  icapps_architecture: ^0.6.0
  injectable: ^1.4.1
  json_annotation: ^4.4.0
  niddler_dart: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  provider: ^6.0.0
  retrofit: ^3.0.0
  scroll_when_needed: ^2.0.0
  shared_preferences: ^2.0.13
  sqlite3_flutter_libs: ^0.5.2
  storage_inspector: ^0.1.1

dev_dependencies:
  build_runner: ^2.1.1
  drift_dev: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  icapps_license: ^2.0.0
  icapps_translations: ^5.2.1
  injectable_generator: ^1.5.0
  json_serializable: ^6.1.1
  mockito: ^5.0.15
  model_generator: ^5.8.1
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

icapps_translations:
  api_key: '16daba4a2cb331e92eeb0aa2fd219608ff7c8f0488ab4aa887411040a951392f9a8cce488463a1f38eeebf96cb06658aa02d43e53cfc7a7be2d652e8' #TODO Update this to the correct api key
  project_id: '43121bf0-0604-4709-aa72-bcc1d19820bf' #TODO Update this to the correct project id
  default_language: 'nl'
  languages: ['nl','en']

icapps_license:
  nullsafety: true
  licenses:
    device_info: 'https://raw.githubusercontent.com/flutter/plugins/master/packages/device_info/device_info/LICENSE'
    flutter_cache_manager: 'https://raw.githubusercontent.com/Baseflow/flutter_cache_manager/develop/flutter_cache_manager/LICENSE'
