name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.9
  connectivity_plus_web: ^1.2.5
  device_info_plus: ^6.0.0
  device_info_plus_web: ^5.0.0
  dio: ^4.0.6
  drift: ^2.4.2
  drift_db_viewer: ^2.0.0
  drift_local_storage_inspector: ^0.5.0
  file_local_storage_inspector: ^0.3.1
  firebase_analytics: ^10.1.0
  firebase_analytics_web: ^0.5.1+8
  firebase_core: ^2.4.1
  firebase_core_web: ^2.1.0
  firebase_crashlytics: ^3.0.10
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  flutter_secure_storage_web: ^1.1.1
  flutter_svg: ^1.1.6
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  icapps_architecture: ^0.8.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  niddler_dart: ^1.6.0
  path: ^1.8.2
  path_provider: ^2.0.11
  preferences_local_storage_inspector: ^0.3.1
  provider: ^6.0.5
  retrofit: ^3.3.1
  scroll_when_needed: ^2.0.0
  secure_storage_local_storage_inspector: ^0.5.0
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.4
  sprintf: ^7.0.0
  sqlite3_flutter_libs: ^0.5.12
  storage_inspector: ^0.3.0
  synchronized: ^3.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.4.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  icapps_license: ^2.0.2
#  icapps_translations: ^9.0.0
  icapps_translations:
    git:
      url: git@github.com:icapps/flutter-icapps-translations.git
      ref: 6bb7c224d030d352ef10d928669cd5150f22058e

  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  license_generator: ^1.0.5
  mockito: ^5.3.2
  model_generator: ^6.0.2
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

icapps_translations:
  api_key: '16daba4a2cb331e92eeb0aa2fd219608ff7c8f0488ab4aa887411040a951392f9a8cce488463a1f38eeebf96cb06658aa02d43e53cfc7a7be2d652e8' #TODO Update this to the correct api key
  project_id: '43121bf0-0604-4709-aa72-bcc1d19820bf' #TODO Update this to the correct project id
  default_language: 'nl'
  languages: [ 'nl','en' ]

license_generator:
  check_before_generate: true