name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  connectivity_plus: ^5.0.2
  connectivity_plus_web: ^1.2.5
  device_info_plus: ^9.0.2
  dio: ^5.3.2
  drift: ^2.18.0
  drift_db_viewer: ^2.0.0
  drift_local_storage_inspector: ^0.7.0
  file_local_storage_inspector: ^0.4.0
  firebase_analytics: ^11.4.1
  firebase_analytics_web: ^0.5.1+8
  firebase_core: ^3.10.1
  firebase_core_web: ^2.1.0
  firebase_crashlytics: ^4.3.1
  firebase_remote_config: ^5.3.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_navigation_generator_annotations: ^2.0.1
  flutter_secure_storage: ^9.2.2
  flutter_secure_storage_web: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  get_it: ^8.0.3
  icapps_architecture: ^2.1.0
  icapps_icons: ^1.0.0
  injectable: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  log_to_secure_file:
    git:
      url: https://github.com/icapps/log_to_secure_file.git
      ref: main
  niddler_dart: ^1.6.0
  path: ^1.8.2
  path_provider: ^2.0.11
  preferences_local_storage_inspector: ^0.4.0
  provider: ^6.0.5
  remote_config_generator: ^0.0.1
  retrofit: ^4.0.1
  scroll_when_needed: ^3.0.1 
  secure_storage_local_storage_inspector: ^0.7.0
  shared_preferences: ^2.0.16
  shared_preferences_web: ^2.0.4
  sprintf: ^7.0.0
  storage_inspector: ^0.4.0
  synchronized: ^3.3.0+3
  url_launcher: ^6.3.1
  widget_book_widget_generator_annotations: ^1.1.0
  widgetbook: ^3.10.2
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.18.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_navigation_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  icapps_translations: ^11.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  license_generator: ^2.0.0
  mockito: ^5.3.2
  model_generator: ^7.0.0
  retrofit_generator: ^9.1.5
  widgetbook_generator: ^3.9.1
  widget_book_widget_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/aeonik_pro/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: AeonikPro
      fonts:
        - asset: assets/fonts/aeonik_pro/AeonikPro-Regular.otf
        - asset: assets/fonts/aeonik_pro/AeonikPro-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik_pro/AeonikPro-Medium.otf
          weight: 500
        - asset: assets/fonts/aeonik_pro/AeonikPro-Bold.otf
          weight: 700
    - family: icappsIcons
      fonts:
        - asset: packages/icapps_icons/fonts/icappsIcons.ttf

icapps_translations:
  api_key: '16daba4a2cb331e92eeb0aa2fd219608ff7c8f0488ab4aa887411040a951392f9a8cce488463a1f38eeebf96cb06658aa02d43e53cfc7a7be2d652e8' #TODO Update this to the correct api key
  project_id: '43121bf0-0604-4709-aa72-bcc1d19820bf' #TODO Update this to the correct project id
  default_language: 'nl'
  languages: [ 'nl','en' ]

license_generator:
  check_before_generate: true